"""
Dataset is generated by scripts/data/{build_pdok_wms_dataset.py,convert_pdok_polylines_to_yolo_seg.py}
"""

from ultralytics import YOLO


def main():
    model = YOLO("yolo26n-seg.pt")

    # Load matching weights from the trained detection checkpoint
    model = model.load(
        "/home/fatemeh/Downloads/hedge/snellius/detect_ultralytics/3/best.pt"
    )

    model.train(
        data="/home/fatemeh/Downloads/hedge/results/pdok_dataset_yolo_seg2/dataset.yaml",
        save_dir="/home/fatemeh/Downloads/hedge/results/training/seg_ultralytics/1",
        imgsz=1000,
        epochs=1,
        batch=4,
        # device=[0, 1, 2, 3],
    )


if __name__ == "__main__":
    main()


"""
import cv2
import matplotlib.pyplot as plt

image_path = "/home/fatemeh/Downloads/cats.jpg" #"/home/fatemeh/Downloads/hedge/results/pdok_dataset_yolo_seg2/images/train/pos_000004.png"
model = YOLO("yolo26n-seg.pt") #YOLO("/home/fatemeh/Downloads/hedge/results/training/seg_ultralytics/1/weights/best.pt")
results = model(image_path, conf=0.25, imgsz=1600) 
result = results[0] # only one image
# Visualize the segmentation outlines
im = cv2.imread(image_path)
plt.figure()
plt.imshow(im)
for r in result:
    plt.plot(r.masks.xy[0][:,0], r.masks.xy[0][:,1], "*r")
    print(r.boxes.xyxy)
plt.show(block=False)

# Visualize the segmentation masks
annotated = result.plot()
plt.figure()
plt.imshow(annotated[..., ::-1])  # BGR to RGB
plt.axis("off")
print("Done")
"""
