"""
Train YOLO instance segmentation on high-resolution aerial imagery with polyline-derived masks.

Data: High-resolution PDOK aerial crops (25 cm/px) with polylines buffered to 15 m radius as instance masks.
Dataset: Generated by scripts/data/{build_pdok_wms_dataset.py,convert_pdok_polylines_to_yolo_seg.py}.
Purpose: Segment hedgerow instances; initialized from detection checkpoint (train_detect_ultralytics.py).
"""

# """
from ultralytics import YOLO


def main():
    model = YOLO("yolo26n-seg.pt")

    # Load matching weights from the trained detection checkpoint
    model = model.load(
        "/home/fatemeh/Downloads/hedge/snellius/detect_ultralytics/3/best.pt"
    )

    model.train(
        data="/home/fatemeh/Downloads/hedge/results/pdok_dataset_yolo_seg2/dataset.yaml",
        save_dir="/home/fatemeh/Downloads/hedge/results/training/seg_ultralytics/1",
        imgsz=1000,
        epochs=1,
        batch=4,
        # device=[0, 1, 2, 3],
        # resume=True # To resume the exact same run, including optimizer state and scheduler state
    )


if __name__ == "__main__":
    main()
# """

"""
# Inference and visualize results

import cv2
import matplotlib.pyplot as plt
import pandas as pd
from ultralytics import YOLO

df = pd.read_csv(
    "/home/fatemeh/Downloads/hedge/snellius/detect_ultralytics/3/results.csv"
)


def plot_train_val_metrics(
    metric_name,
):  # plot train/box_loss,train/seg_loss,train/cls_loss,train/dfl_loss,train/sem_loss,val/box_loss,val/seg_loss,val/cls_loss,val/dfl_loss,val/sem_loss
    plt.figure()
    plt.plot(df[f"train/{metric_name}"], "*-", label="train")
    plt.plot(df[f"val/{metric_name}"], "*-", label="val")
    plt.title(metric_name)
    plt.legend()
    plt.show(block=False)


def plot_metrics(
    metric_name,
):  # plot metrics/precision(B),metrics/recall(B),metrics/mAP50(B),metrics/mAP50-95(B)
    plt.figure()
    plt.plot(df[f"metrics/{metric_name}(B)"], "*-", label="B")
    plt.plot(df[f"metrics/{metric_name}(M)"], "*-", label="M")
    plt.title(metric_name)
    plt.legend()
    plt.show(block=False)


# epoch,time,train/box_loss,train/seg_loss,train/cls_loss,train/dfl_loss,train/sem_loss,
# metrics/precision(B),metrics/recall(B),metrics/mAP50(B),metrics/mAP50-95(B),metrics/precision(M),metrics/recall(M),metrics/mAP50(M),metrics/mAP50-95(M),
# val/box_loss,val/seg_loss,val/cls_loss,val/dfl_loss,val/sem_loss,
# lr/pg0,lr/pg1,lr/pg2,lr/pg3,lr/pg4,lr/pg5,lr/pg6,lr/pg7


# epoch,time,train/box_loss,train/cls_loss,train/dfl_loss,
# metrics/precision(B),metrics/recall(B),metrics/mAP50(B),metrics/mAP50-95(B),
# val/box_loss,val/cls_loss,val/dfl_loss,
# lr/pg0,lr/pg1,lr/pg2,lr/pg3,lr/pg4,lr/pg5,lr/pg6,lr/pg7

# plot_train_val_metrics("box_loss")
# plot_train_val_metrics("seg_loss")
# plot_train_val_metrics("cls_loss")
# plot_train_val_metrics("dfl_loss")
# plot_train_val_metrics("sem_loss")
# plot_metrics("precision")
# plot_metrics("recall")
# plot_metrics("mAP50")
# plot_metrics("mAP50-95")


image_path = "/home/fatemeh/Downloads/cats.jpg"  # "/home/fatemeh/Downloads/hedge/results/pdok_dataset_yolo_seg2/images/train/pos_000004.png"
# model = YOLO("yolo26n-seg.pt") #YOLO("/home/fatemeh/Downloads/hedge/results/training/seg_ultralytics/1/weights/best.pt")
image_path = "/home/fatemeh/Downloads/hedge/results/pdok_dataset_yolo_seg2/images/train/pos_000004.png"
model = YOLO("/home/fatemeh/Downloads/hedge/snellius/seg_ultralytics/1/best.pt")
results = model(image_path, conf=0.25, imgsz=1000)
result = results[0]  # only one image
# Visualize the segmentation outlines
im = cv2.imread(image_path)
plt.figure()
plt.imshow(im)
for r in result:
    plt.plot(r.masks.xy[0][:, 0], r.masks.xy[0][:, 1], "*r")
    print(r.boxes.xyxy)
plt.show(block=False)

# Visualize the segmentation masks
annotated = result.plot()
plt.figure()
plt.imshow(annotated[..., ::-1])  # BGR to RGB
plt.axis("off")

from pathlib import Path

from hedge_seg.visualization import draw_yolo_segmentation_on_image

main_path = Path("/home/fatemeh/Downloads/hedge/results/pdok_dataset_yolo_seg2")
draw_yolo_segmentation_on_image(main_path, 4, folder="train")
print("Done")
"""
