"""
Dataset is generated by scripts/data/{build_pdok_wms_dataset.py,convert_to_ultralytics_format.py}
"""

from ultralytics import YOLO


def main():
    model = YOLO("yolo26x.pt")
    model.train(
        # data="/home/fkarimineja/data/hedge/pdok_dataset_yolo/dataset.yaml",
        data="/home/fatemeh/Downloads/hedge/results/pdok_dataset_yolo/dataset.yaml",
        epochs=1,
        imgsz=1000,
    )


if __name__ == "__main__":
    main()


# yolo predict model=/home/fatemeh/Downloads/hedge/snellius/detect_ultralytics/3/best.pt conf=.25 imgsz=1000 save_dir=/home/fatemeh/Downloads/hedge/snellius/detect_ultralytics/3 save=True  source=/home/fatemeh/Downloads/hedge/results/pdok_dataset_yolo3/images/val/pos_000004.png
