"""
DETR-style polyline detector. Descends from train_detr_dino_polyline_rel.py
(now superseded) with these changes:

MapTR-style head (was: DINO-style flat polyline queries + diffusion refinement):
- Hierarchical queries: separate instance embedding + point embedding, so both
  the query position and the query content are learned per (instance, point).
- Iterative reference-point refinement in the decoder: each layer refines the
  previous layer's points and rebuilds the query positional embedding from the
  current reference point (MapTR-style, but with global attention, not
  deformable attention).
- Diffusion refinement stage removed.
- Geometric losses (bbox L1/gIoU, length, direction, smoothness, cardinality)
  are optional and off by default; only class + ordered point L1 (+ aux) are
  used. When length/direction are enabled, the forward/reverse GT orientation
  is chosen by the same ordered-L1 criterion as the polyline loss.

UNet-ResNet18 image backbone (was: precomputed DINOv3 embeddings of LiDAR crops), 
similar code as train_detr_maptr_polyline.py with these changes:
- Backbone on high-resolution PDOK aerial images (25 cm/px, 1000 x 1000),
  initialized from the train_semseg_unet_resnet18.py semseg checkpoint,
  freezable (frozen keeps BatchNorm in eval so semseg statistics are preserved).
- Dataset loads images + polyline NPZs produced by
  scripts/data/convert_pdok_polylines_to_detr_polyline.py.
- Images are zero-padded 1000 -> pad_to (default 1024, divisible by 32);
  polylines are normalized by the padded extent so they stay aligned with
  the feature grid.
- Optional flip/rot90 augmentation of image + polylines together.
- mode="preview" renders exactly what the model sees (padded, normalized,
  augmented image tensor + GT polylines) for visual verification.

Dataset: Generated by scripts/data/{build_pdok_wms_dataset.py,convert_pdok_polylines_to_detr_polyline.py}.
"""

import copy
from contextlib import nullcontext
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
from omegaconf import OmegaConf
from PIL import Image
from scipy.optimize import linear_sum_assignment
from torch.utils import tensorboard
from torch.utils.data import DataLoader, Dataset
from tqdm import tqdm

from hedge_seg.training_utils import set_seed

IMAGENET_MEAN = torch.tensor([0.485, 0.456, 0.406]).view(3, 1, 1)
IMAGENET_STD = torch.tensor([0.229, 0.224, 0.225]).view(3, 1, 1)

# -------------------------
# Utilities: boxes
# -------------------------


def box_area_xyxy(boxes: torch.Tensor) -> torch.Tensor:
    return (boxes[:, 2] - boxes[:, 0]).clamp(min=0) * (boxes[:, 3] - boxes[:, 1]).clamp(
        min=0
    )


def box_iou_xyxy(
    boxes1: torch.Tensor, boxes2: torch.Tensor
) -> Tuple[torch.Tensor, torch.Tensor]:
    area1 = box_area_xyxy(boxes1)
    area2 = box_area_xyxy(boxes2)

    lt = torch.max(boxes1[:, None, :2], boxes2[None, :, :2])  # (N,M,2)
    rb = torch.min(boxes1[:, None, 2:], boxes2[None, :, 2:])  # (N,M,2)

    wh = (rb - lt).clamp(min=0)
    inter = wh[:, :, 0] * wh[:, :, 1]

    union = area1[:, None] + area2[None, :] - inter
    iou = inter / union.clamp(min=1e-6)
    return iou, union


def generalized_box_iou_xyxy(
    boxes1: torch.Tensor, boxes2: torch.Tensor
) -> torch.Tensor:
    iou, union = box_iou_xyxy(boxes1, boxes2)

    lt = torch.min(boxes1[:, None, :2], boxes2[None, :, :2])
    rb = torch.max(boxes1[:, None, 2:], boxes2[None, :, 2:])

    wh = (rb - lt).clamp(min=0)
    area_c = wh[:, :, 0] * wh[:, :, 1]
    return iou - (area_c - union) / area_c.clamp(min=1e-6)


def polyline_to_bbox_xyxy(poly: torch.Tensor) -> torch.Tensor:
    """
    poly: (..., K, 2) normalized in [0,1]
    returns: (..., 4) xyxy normalized
    """
    x = poly[..., :, 0]
    y = poly[..., :, 1]
    x0 = x.min(dim=-1).values
    y0 = y.min(dim=-1).values
    x1 = x.max(dim=-1).values
    y1 = y.max(dim=-1).values
    return torch.stack([x0, y0, x1, y1], dim=-1)


def box_xyxy_to_cxcywh(boxes: torch.Tensor) -> torch.Tensor:
    x0, y0, x1, y1 = boxes.unbind(-1)
    cx = (x0 + x1) * 0.5
    cy = (y0 + y1) * 0.5
    w = (x1 - x0).clamp(min=1e-6)
    h = (y1 - y0).clamp(min=1e-6)
    return torch.stack([cx, cy, w, h], dim=-1)


def box_cxcywh_to_xyxy(boxes: torch.Tensor) -> torch.Tensor:
    cx, cy, w, h = boxes.unbind(-1)
    x0 = cx - 0.5 * w
    y0 = cy - 0.5 * h
    x1 = cx + 0.5 * w
    y1 = cy + 0.5 * h
    return torch.stack([x0, y0, x1, y1], dim=-1)


def inverse_sigmoid(x: torch.Tensor, eps: float = 1e-5) -> torch.Tensor:
    x = x.clamp(min=eps, max=1.0 - eps)
    return torch.log(x / (1.0 - x))


def gen_sineembed_for_position(
    pos: torch.Tensor, num_pos_feats: int = 128, temperature: int = 10000
) -> torch.Tensor:
    """
    Sine embedding for continuous 2D positions (DAB/Conditional-DETR style).

    pos: (..., 2) normalized in [0,1]
    returns: (..., 2*num_pos_feats), cat(pos_y, pos_x) to match PositionEmbeddingSine2D
    """
    scale = 2 * torch.pi
    dim_t = torch.arange(num_pos_feats, dtype=torch.float32, device=pos.device)
    dim_t = temperature ** (2 * (dim_t // 2) / num_pos_feats)

    x_embed = pos[..., 0] * scale
    y_embed = pos[..., 1] * scale
    pos_x = x_embed[..., None] / dim_t
    pos_y = y_embed[..., None] / dim_t

    pos_x = torch.stack(
        (pos_x[..., 0::2].sin(), pos_x[..., 1::2].cos()), dim=-1
    ).flatten(-2)
    pos_y = torch.stack(
        (pos_y[..., 0::2].sin(), pos_y[..., 1::2].cos()), dim=-1
    ).flatten(-2)
    return torch.cat((pos_y, pos_x), dim=-1)


# -------------------------
# Positional encoding (2D sine)
# -------------------------


class PositionEmbeddingSine2D(nn.Module):
    def __init__(
        self,
        num_pos_feats: int = 128,
        temperature: int = 10000,
        normalize: bool = True,
        scale: Optional[float] = None,
    ):
        super().__init__()
        self.num_pos_feats = num_pos_feats
        self.temperature = temperature
        self.normalize = normalize
        self.scale = scale if scale is not None else 2 * torch.pi

    def forward(self, B: int, H: int, W: int, device: torch.device) -> torch.Tensor:
        y_embed = torch.arange(H, device=device).unsqueeze(1).repeat(1, W)
        x_embed = torch.arange(W, device=device).unsqueeze(0).repeat(H, 1)

        if self.normalize:
            eps = 1e-6
            y_embed = y_embed / (H - 1 + eps) * self.scale
            x_embed = x_embed / (W - 1 + eps) * self.scale

        dim_t = torch.arange(self.num_pos_feats, device=device, dtype=torch.float32)
        dim_t = self.temperature ** (2 * (dim_t // 2) / self.num_pos_feats)

        pos_x = x_embed[..., None] / dim_t
        pos_y = y_embed[..., None] / dim_t

        pos_x = torch.stack(
            (pos_x[..., 0::2].sin(), pos_x[..., 1::2].cos()), dim=-1
        ).flatten(-2)
        pos_y = torch.stack(
            (pos_y[..., 0::2].sin(), pos_y[..., 1::2].cos()), dim=-1
        ).flatten(-2)

        pos = torch.cat((pos_y, pos_x), dim=-1)  # (H,W,D)
        pos = pos.view(H * W, -1).unsqueeze(0).repeat(B, 1, 1)  # (B,HW,D)
        return pos


# -------------------------
# DETR model predicting polylines
# -------------------------


class MLP(nn.Module):
    def __init__(
        self, input_dim: int, hidden_dim: int, output_dim: int, num_layers: int
    ):
        super().__init__()
        layers = []
        for i in range(num_layers):
            in_d = input_dim if i == 0 else hidden_dim
            out_d = output_dim if i == num_layers - 1 else hidden_dim
            layers.append(nn.Linear(in_d, out_d))
        self.layers = nn.ModuleList(layers)

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        for i, layer in enumerate(self.layers):
            x = layer(x)
            if i < len(self.layers) - 1:
                x = F.relu(x)
        return x


# =========================================================
# DETR-style transformer
# =========================================================


def _get_clones(module, N):
    return nn.ModuleList([copy.deepcopy(module) for _ in range(N)])


def _with_pos_embed(tensor: torch.Tensor, pos: Optional[torch.Tensor]):
    return tensor if pos is None else tensor + pos


class DETRTransformer(nn.Module):
    def __init__(
        self,
        d_model=256,
        nhead=8,
        num_encoder_layers=6,
        num_decoder_layers=6,
        dim_feedforward=2048,
        dropout=0.1,
        activation="relu",
        normalize_before=False,
        return_intermediate_dec=True,
    ):
        super().__init__()

        encoder_layer = DETRTransformerEncoderLayer(
            d_model, nhead, dim_feedforward, dropout, activation, normalize_before
        )
        encoder_norm = nn.LayerNorm(d_model) if normalize_before else None
        self.encoder = DETRTransformerEncoder(
            encoder_layer, num_encoder_layers, encoder_norm
        )

        decoder_layer = DETRTransformerDecoderLayer(
            d_model, nhead, dim_feedforward, dropout, activation, normalize_before
        )
        decoder_norm = nn.LayerNorm(d_model)
        self.decoder = DETRTransformerDecoder(
            decoder_layer,
            num_decoder_layers,
            decoder_norm,
            return_intermediate=return_intermediate_dec,
        )

        self._reset_parameters()

    def _reset_parameters(self):
        for p in self.parameters():
            if p.dim() > 1:
                nn.init.xavier_uniform_(p)

    def forward(
        self,
        src: torch.Tensor,  # (B, L, D)
        query_embed: torch.Tensor,  # (Q, D)
        query_content: Optional[torch.Tensor] = None,  # (Q, D)
        pos_embed: Optional[torch.Tensor] = None,  # (B, L, D)
        mask: Optional[torch.Tensor] = None,  # (B, L)
        reference_points: Optional[torch.Tensor] = None,  # (B, Q, 2) in [0,1]
        reg_branches: Optional[nn.ModuleList] = None,  # per-layer offset heads
        ref_point_head: Optional[nn.Module] = None,  # sine embed -> query_pos MLP
    ):
        B, _, _ = src.shape
        query_embed = query_embed.unsqueeze(0).expand(B, -1, -1)  # (B,Q,D)
        if query_content is None:
            tgt = torch.zeros_like(query_embed)
        else:
            tgt = query_content.unsqueeze(0).expand(B, -1, -1)  # (B,Q,D)

        memory = self.encoder(src, src_key_padding_mask=mask, pos=pos_embed)
        hs, refs = self.decoder(
            tgt,
            memory,
            memory_key_padding_mask=mask,
            pos=pos_embed,
            query_pos=query_embed,
            reference_points=reference_points,
            reg_branches=reg_branches,
            ref_point_head=ref_point_head,
        )
        # hs: (num_layers, B, Q, D); refs: (num_layers, B, Q, 2) or None
        return hs, refs, memory


class DETRTransformerEncoder(nn.Module):
    def __init__(self, encoder_layer, num_layers, norm=None):
        super().__init__()
        self.layers = _get_clones(encoder_layer, num_layers)
        self.norm = norm

    def forward(
        self,
        src,
        mask: Optional[torch.Tensor] = None,
        src_key_padding_mask: Optional[torch.Tensor] = None,
        pos: Optional[torch.Tensor] = None,
    ):
        output = src
        for layer in self.layers:
            output = layer(
                output,
                src_mask=mask,
                src_key_padding_mask=src_key_padding_mask,
                pos=pos,
            )
        if self.norm is not None:
            output = self.norm(output)
        return output


class DETRTransformerDecoder(nn.Module):
    def __init__(self, decoder_layer, num_layers, norm=None, return_intermediate=False):
        super().__init__()
        self.layers = _get_clones(decoder_layer, num_layers)
        self.norm = norm
        self.return_intermediate = return_intermediate

    def forward(
        self,
        tgt,
        memory,
        tgt_mask: Optional[torch.Tensor] = None,
        memory_mask: Optional[torch.Tensor] = None,
        tgt_key_padding_mask: Optional[torch.Tensor] = None,
        memory_key_padding_mask: Optional[torch.Tensor] = None,
        pos: Optional[torch.Tensor] = None,
        query_pos: Optional[torch.Tensor] = None,
        reference_points: Optional[torch.Tensor] = None,  # (B, Q, 2) in [0,1]
        reg_branches: Optional[nn.ModuleList] = None,
        ref_point_head: Optional[nn.Module] = None,
    ):
        refine = reference_points is not None
        if refine:
            assert reg_branches is not None and ref_point_head is not None
            assert len(reg_branches) == len(self.layers)

        output = tgt
        ref = reference_points
        intermediate = []
        intermediate_refs = []

        for lid, layer in enumerate(self.layers):
            if refine:
                # Query positional embedding follows the current point location,
                # so attention is conditioned on where each point currently is.
                d_model = output.shape[-1]
                query_sine = gen_sineembed_for_position(
                    ref, num_pos_feats=d_model // 2
                )  # (B,Q,D)
                layer_query_pos = ref_point_head(query_sine)
            else:
                layer_query_pos = query_pos

            output = layer(
                output,
                memory,
                tgt_mask=tgt_mask,
                memory_mask=memory_mask,
                tgt_key_padding_mask=tgt_key_padding_mask,
                memory_key_padding_mask=memory_key_padding_mask,
                pos=pos,
                query_pos=layer_query_pos,
            )
            out_normed = self.norm(output) if self.norm is not None else output

            if refine:
                delta = reg_branches[lid](out_normed)  # (B,Q,2)
                new_ref = (delta + inverse_sigmoid(ref)).sigmoid()
                intermediate_refs.append(new_ref)
                ref = new_ref.detach()

            if self.return_intermediate:
                intermediate.append(out_normed)

        if self.return_intermediate:
            hs = torch.stack(intermediate)
            refs = torch.stack(intermediate_refs) if refine else None
            return hs, refs

        hs = out_normed.unsqueeze(0)
        refs = intermediate_refs[-1].unsqueeze(0) if refine else None
        return hs, refs


class DETRTransformerEncoderLayer(nn.Module):
    def __init__(
        self,
        d_model,
        nhead,
        dim_feedforward=2048,
        dropout=0.1,
        activation="relu",
        normalize_before=False,
    ):
        super().__init__()
        self.self_attn = nn.MultiheadAttention(
            d_model, nhead, dropout=dropout, batch_first=True
        )

        self.linear1 = nn.Linear(d_model, dim_feedforward)
        self.dropout = nn.Dropout(dropout)
        self.linear2 = nn.Linear(dim_feedforward, d_model)

        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.dropout1 = nn.Dropout(dropout)
        self.dropout2 = nn.Dropout(dropout)

        self.activation = F.relu if activation == "relu" else F.gelu
        self.normalize_before = normalize_before

    def forward_post(
        self,
        src,
        src_mask: Optional[torch.Tensor] = None,
        src_key_padding_mask: Optional[torch.Tensor] = None,
        pos: Optional[torch.Tensor] = None,
    ):
        q = k = _with_pos_embed(src, pos)
        src2 = self.self_attn(
            q,
            k,
            value=src,
            attn_mask=src_mask,
            key_padding_mask=src_key_padding_mask,
            need_weights=False,
        )[0]
        src = src + self.dropout1(src2)
        src = self.norm1(src)

        src2 = self.linear2(self.dropout(self.activation(self.linear1(src))))
        src = src + self.dropout2(src2)
        src = self.norm2(src)
        return src

    def forward_pre(
        self,
        src,
        src_mask: Optional[torch.Tensor] = None,
        src_key_padding_mask: Optional[torch.Tensor] = None,
        pos: Optional[torch.Tensor] = None,
    ):
        src2 = self.norm1(src)
        q = k = _with_pos_embed(src2, pos)
        src2 = self.self_attn(
            q,
            k,
            value=src2,
            attn_mask=src_mask,
            key_padding_mask=src_key_padding_mask,
            need_weights=False,
        )[0]
        src = src + self.dropout1(src2)

        src2 = self.norm2(src)
        src2 = self.linear2(self.dropout(self.activation(self.linear1(src2))))
        src = src + self.dropout2(src2)
        return src

    def forward(
        self,
        src,
        src_mask: Optional[torch.Tensor] = None,
        src_key_padding_mask: Optional[torch.Tensor] = None,
        pos: Optional[torch.Tensor] = None,
    ):
        if self.normalize_before:
            return self.forward_pre(src, src_mask, src_key_padding_mask, pos)
        return self.forward_post(src, src_mask, src_key_padding_mask, pos)


class DETRTransformerDecoderLayer(nn.Module):
    def __init__(
        self,
        d_model,
        nhead,
        dim_feedforward=2048,
        dropout=0.1,
        activation="relu",
        normalize_before=False,
    ):
        super().__init__()
        self.self_attn = nn.MultiheadAttention(
            d_model, nhead, dropout=dropout, batch_first=True
        )
        self.multihead_attn = nn.MultiheadAttention(
            d_model, nhead, dropout=dropout, batch_first=True
        )

        self.linear1 = nn.Linear(d_model, dim_feedforward)
        self.dropout = nn.Dropout(dropout)
        self.linear2 = nn.Linear(dim_feedforward, d_model)

        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.norm3 = nn.LayerNorm(d_model)
        self.dropout1 = nn.Dropout(dropout)
        self.dropout2 = nn.Dropout(dropout)
        self.dropout3 = nn.Dropout(dropout)

        self.activation = F.relu if activation == "relu" else F.gelu
        self.normalize_before = normalize_before

    def forward_post(
        self,
        tgt,
        memory,
        tgt_mask: Optional[torch.Tensor] = None,
        memory_mask: Optional[torch.Tensor] = None,
        tgt_key_padding_mask: Optional[torch.Tensor] = None,
        memory_key_padding_mask: Optional[torch.Tensor] = None,
        pos: Optional[torch.Tensor] = None,
        query_pos: Optional[torch.Tensor] = None,
    ):
        q = k = _with_pos_embed(tgt, query_pos)
        tgt2 = self.self_attn(
            q,
            k,
            value=tgt,
            attn_mask=tgt_mask,
            key_padding_mask=tgt_key_padding_mask,
            need_weights=False,
        )[0]
        tgt = tgt + self.dropout1(tgt2)
        tgt = self.norm1(tgt)

        tgt2 = self.multihead_attn(
            query=_with_pos_embed(tgt, query_pos),
            key=_with_pos_embed(memory, pos),
            value=memory,
            attn_mask=memory_mask,
            key_padding_mask=memory_key_padding_mask,
            need_weights=False,
        )[0]
        tgt = tgt + self.dropout2(tgt2)
        tgt = self.norm2(tgt)

        tgt2 = self.linear2(self.dropout(self.activation(self.linear1(tgt))))
        tgt = tgt + self.dropout3(tgt2)
        tgt = self.norm3(tgt)
        return tgt

    def forward_pre(
        self,
        tgt,
        memory,
        tgt_mask: Optional[torch.Tensor] = None,
        memory_mask: Optional[torch.Tensor] = None,
        tgt_key_padding_mask: Optional[torch.Tensor] = None,
        memory_key_padding_mask: Optional[torch.Tensor] = None,
        pos: Optional[torch.Tensor] = None,
        query_pos: Optional[torch.Tensor] = None,
    ):
        tgt2 = self.norm1(tgt)
        q = k = _with_pos_embed(tgt2, query_pos)
        tgt2 = self.self_attn(
            q,
            k,
            value=tgt2,
            attn_mask=tgt_mask,
            key_padding_mask=tgt_key_padding_mask,
            need_weights=False,
        )[0]
        tgt = tgt + self.dropout1(tgt2)

        tgt2 = self.norm2(tgt)
        tgt2 = self.multihead_attn(
            query=_with_pos_embed(tgt2, query_pos),
            key=_with_pos_embed(memory, pos),
            value=memory,
            attn_mask=memory_mask,
            key_padding_mask=memory_key_padding_mask,
            need_weights=False,
        )[0]
        tgt = tgt + self.dropout2(tgt2)

        tgt2 = self.norm3(tgt)
        tgt2 = self.linear2(self.dropout(self.activation(self.linear1(tgt2))))
        tgt = tgt + self.dropout3(tgt2)
        return tgt

    def forward(
        self,
        tgt,
        memory,
        tgt_mask: Optional[torch.Tensor] = None,
        memory_mask: Optional[torch.Tensor] = None,
        tgt_key_padding_mask: Optional[torch.Tensor] = None,
        memory_key_padding_mask: Optional[torch.Tensor] = None,
        pos: Optional[torch.Tensor] = None,
        query_pos: Optional[torch.Tensor] = None,
    ):
        if self.normalize_before:
            return self.forward_pre(
                tgt,
                memory,
                tgt_mask,
                memory_mask,
                tgt_key_padding_mask,
                memory_key_padding_mask,
                pos,
                query_pos,
            )
        return self.forward_post(
            tgt,
            memory,
            tgt_mask,
            memory_mask,
            tgt_key_padding_mask,
            memory_key_padding_mask,
            pos,
            query_pos,
        )


# =========================================================
# Legacy mode transformer wrapper
# =========================================================


class LegacyTransformerWrapper(nn.Module):
    """
    Your original style:
      - add pos before encoder
      - add query to tgt before decoder
      - optionally collect intermediate decoder layers
    """

    def __init__(
        self,
        d_model=256,
        nhead=8,
        num_encoder_layers=6,
        num_decoder_layers=6,
        dim_feedforward=2048,
        dropout=0.1,
        return_intermediate_dec=True,
    ):
        super().__init__()

        enc_layer = nn.TransformerEncoderLayer(
            d_model=d_model,
            nhead=nhead,
            dim_feedforward=dim_feedforward,
            dropout=dropout,
            batch_first=True,
        )
        self.encoder = nn.TransformerEncoder(enc_layer, num_layers=num_encoder_layers)

        dec_layer = nn.TransformerDecoderLayer(
            d_model=d_model,
            nhead=nhead,
            dim_feedforward=dim_feedforward,
            dropout=dropout,
            batch_first=True,
        )
        self.decoder = nn.TransformerDecoder(dec_layer, num_layers=num_decoder_layers)

        self.return_intermediate_dec = return_intermediate_dec

    def forward(
        self,
        src: torch.Tensor,  # (B,L,D)
        query_embed: torch.Tensor,  # (Q,D)
        query_content: Optional[torch.Tensor] = None,  # (Q,D)
        pos_embed: Optional[torch.Tensor] = None,  # (B,L,D)
        mask: Optional[torch.Tensor] = None,  # (B,L)
        reference_points: Optional[torch.Tensor] = None,  # unsupported, must be None
        reg_branches: Optional[nn.ModuleList] = None,
        ref_point_head: Optional[nn.Module] = None,
    ):
        assert reference_points is None, "legacy mode does not support refinement"
        B, _, _ = src.shape

        if pos_embed is not None:
            src = src + pos_embed

        memory = self.encoder(src, src_key_padding_mask=mask)

        query = query_embed.unsqueeze(0).expand(B, -1, -1)  # (B,Q,D)
        if query_content is None:
            output = torch.zeros_like(query) + query
        else:
            output = query_content.unsqueeze(0).expand(B, -1, -1) + query

        if self.return_intermediate_dec:
            intermediate = []
            for layer in self.decoder.layers:
                output = layer(
                    output,
                    memory,
                    tgt_key_padding_mask=None,
                    memory_key_padding_mask=mask,
                )
                intermediate.append(
                    self.decoder.norm(output)
                    if self.decoder.norm is not None
                    else output
                )
            hs = torch.stack(intermediate)  # (num_layers,B,Q,D)
        else:
            output = self.decoder(
                output,
                memory,
                tgt_key_padding_mask=None,
                memory_key_padding_mask=mask,
            )
            hs = output.unsqueeze(0)

        return hs, None, memory


# =========================================================
# UNet-ResNet18 backbone (copied from train_semseg_unet_resnet18.py so the
# semantic-segmentation checkpoint loads with strict=True)
# =========================================================


class ConvBlock(nn.Module):
    def __init__(self, in_channels: int, out_channels: int):
        super().__init__()

        self.block = nn.Sequential(
            nn.Conv2d(in_channels, out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
            nn.Conv2d(out_channels, out_channels, kernel_size=3, padding=1, bias=False),
            nn.BatchNorm2d(out_channels),
            nn.ReLU(inplace=True),
        )

    def forward(self, x):
        return self.block(x)


class UpBlock(nn.Module):
    def __init__(self, in_channels: int, skip_channels: int, out_channels: int):
        super().__init__()

        self.conv = ConvBlock(in_channels + skip_channels, out_channels)

    def forward(self, x, skip):
        x = F.interpolate(x, size=skip.shape[-2:], mode="bilinear", align_corners=False)
        x = torch.cat([x, skip], dim=1)
        x = self.conv(x)
        return x


class ResNet18UNet(nn.Module):
    def __init__(
        self,
        out_channels: int = 2,
        pretrained: bool = False,
    ):
        super().__init__()

        if pretrained:
            weights = torchvision.models.ResNet18_Weights.DEFAULT
        else:
            weights = None

        resnet = torchvision.models.resnet18(weights=weights)

        self.stem = nn.Sequential(
            resnet.conv1,
            resnet.bn1,
            resnet.relu,
        )
        self.maxpool = resnet.maxpool

        self.enc1 = resnet.layer1  # 64 channels, stride 4 after maxpool
        self.enc2 = resnet.layer2  # 128 channels, stride 8
        self.enc3 = resnet.layer3  # 256 channels, stride 16
        self.enc4 = resnet.layer4  # 512 channels, stride 32

        self.up3 = UpBlock(in_channels=512, skip_channels=256, out_channels=256)
        self.up2 = UpBlock(in_channels=256, skip_channels=128, out_channels=128)
        self.up1 = UpBlock(in_channels=128, skip_channels=64, out_channels=64)
        self.up0 = UpBlock(in_channels=64, skip_channels=64, out_channels=64)

        self.head = nn.Conv2d(64, out_channels, kernel_size=1)


FEATURE_STAGES = {
    "enc4": {"stride": 32, "channels": 512},
    "up3": {"stride": 16, "channels": 256},
}


class ResNet18UNetFeatures(nn.Module):
    """
    Feature extractor on top of the semseg-trained ResNet18UNet.

    feature_stage:
      "enc4": stride 32, 512 channels (cheapest)
      "up3":  stride 16, 256 channels (higher resolution for thin polylines)

    When frozen, parameters get no gradient and BatchNorm stays in eval mode
    so running statistics are not updated by the polyline training data.
    """

    def __init__(
        self,
        ckpt_path: Optional[Path] = None,
        feature_stage: str = "up3",
        frozen: bool = True,
    ):
        super().__init__()
        assert feature_stage in FEATURE_STAGES
        self.feature_stage = feature_stage
        self.frozen = frozen
        self.stride = FEATURE_STAGES[feature_stage]["stride"]
        self.out_channels = FEATURE_STAGES[feature_stage]["channels"]

        self.unet = ResNet18UNet(out_channels=2, pretrained=False)
        if ckpt_path is not None:
            # weights_only=False: the semseg checkpoint stores its cfg (with
            # PosixPath objects) next to the state dict.
            ckpt = torch.load(ckpt_path, map_location="cpu", weights_only=False)
            state = ckpt["model"] if "model" in ckpt else ckpt
            self.unet.load_state_dict(state, strict=True)
            print(f"Loaded backbone checkpoint from {ckpt_path}")

        if frozen:
            for p in self.unet.parameters():
                p.requires_grad_(False)

    def train(self, mode: bool = True):
        super().train(mode)
        if self.frozen:
            self.unet.eval()
        return self

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        ctx = torch.no_grad() if self.frozen else nullcontext()
        with ctx:
            s0 = self.unet.stem(x)
            x = self.unet.maxpool(s0)
            s1 = self.unet.enc1(x)
            s2 = self.unet.enc2(s1)
            s3 = self.unet.enc3(s2)
            x4 = self.unet.enc4(s3)

            if self.feature_stage == "enc4":
                return x4  # (B,512,H/32,W/32)
            return self.unet.up3(x4, s3)  # (B,256,H/16,W/16)


# =========================================================
# Polyline model with switchable query/pos style
# =========================================================


class DetrPolylineFromEmbeddings(nn.Module):
    """
    Input: x (B, L, in_dim), with L = grid_h * grid_w
    Output:
      pred_logits: (B, P, num_classes+1)
      pred_boxes: (B, P, 4) in [0,1], cxcywh
      pred_polylines: (B, P, K, 2) in [0,1]
      aux_outputs: list[dict], optional

    MapTR-style query layout:
      instance_embedding: (P, 2D)
      pts_embedding: (K, 2D)
      object_query_embed: (P*K, 2D), split into query_pos/query_content
      decoder hs: (num_layers, B, P*K, D) -> (num_layers, B, P, K, D)
    """

    def __init__(
        self,
        in_dim: int = 1024,
        num_classes: int = 1,
        num_polylines: int = 100,
        d_model: int = 256,
        nhead: int = 8,
        num_encoder_layers: int = 4,
        num_decoder_layers: int = 4,
        dim_feedforward: int = 1024,
        dropout: float = 0.1,
        grid_size: Tuple[int, int] = (16, 16),
        num_points: int = 20,
        aux_loss: bool = True,
        normalize_before: bool = False,
        query_embed_mode: str = "detr",  # "detr" or "legacy"
        with_refine: bool = True,
    ):
        super().__init__()
        assert query_embed_mode in {"detr", "legacy"}
        if with_refine and query_embed_mode != "detr":
            raise ValueError("with_refine=True requires query_embed_mode='detr'")

        self.num_classes = num_classes
        self.num_polylines = num_polylines
        self.num_queries = num_polylines * num_points
        self.grid_h, self.grid_w = grid_size
        self.num_points = num_points
        self.aux_loss = aux_loss
        self.query_embed_mode = query_embed_mode
        self.with_refine = with_refine

        self.input_proj = nn.Linear(in_dim, d_model)
        self.pos_embed = PositionEmbeddingSine2D(num_pos_feats=d_model // 2)
        self.instance_embedding = nn.Embedding(num_polylines, d_model * 2)
        self.pts_embedding = nn.Embedding(num_points, d_model * 2)

        if query_embed_mode == "detr":
            self.transformer = DETRTransformer(
                d_model=d_model,
                nhead=nhead,
                num_encoder_layers=num_encoder_layers,
                num_decoder_layers=num_decoder_layers,
                dim_feedforward=dim_feedforward,
                dropout=dropout,
                normalize_before=normalize_before,
                return_intermediate_dec=aux_loss,
            )
        else:
            self.transformer = LegacyTransformerWrapper(
                d_model=d_model,
                nhead=nhead,
                num_encoder_layers=num_encoder_layers,
                num_decoder_layers=num_decoder_layers,
                dim_feedforward=dim_feedforward,
                dropout=dropout,
                return_intermediate_dec=aux_loss,
            )

        self.class_embed = nn.Linear(d_model, num_classes + 1)
        self.reference_points = nn.Linear(d_model, 2)

        if with_refine:
            # Maps sine embedding of current reference point -> query_pos, per layer.
            self.ref_point_head = MLP(d_model, d_model, d_model, num_layers=2)
            # One offset head per decoder layer (MapTR-style iterative refinement).
            self.reg_branches = _get_clones(
                MLP(d_model, d_model, 2, num_layers=3), num_decoder_layers
            )
            # Zero-init so refinement starts as identity: layer outputs equal the
            # initial reference points, and offsets grow from zero.
            for reg in self.reg_branches:
                nn.init.zeros_(reg.layers[-1].weight)
                nn.init.zeros_(reg.layers[-1].bias)
        else:
            self.point_embed = MLP(d_model, d_model, 2, num_layers=3)

    def _build_hierarchical_queries(self) -> Tuple[torch.Tensor, torch.Tensor]:
        pts_embeds = self.pts_embedding.weight.unsqueeze(0)  # (1,K,2D)
        instance_embeds = self.instance_embedding.weight.unsqueeze(1)  # (P,1,2D)
        object_query_embed = (pts_embeds + instance_embeds).flatten(0, 1)  # (P*K,2D)
        query_pos, query_content = object_query_embed.chunk(2, dim=-1)  # (P*K,D)
        return query_pos, query_content

    def _decode_polylines(
        self,
        hs: torch.Tensor,  # (num_layers,B,P*K,D)
        query_pos: torch.Tensor,  # (P*K,D)
    ) -> torch.Tensor:
        reference_points = self.reference_points(query_pos).sigmoid()  # (P*K,2)
        point_logits = self.point_embed(hs)  # (num_layers,B,P*K,2)
        point_logits = point_logits + inverse_sigmoid(reference_points)[None, None]
        points = point_logits.sigmoid()

        return points.view(
            hs.shape[0],
            hs.shape[1],
            self.num_polylines,
            self.num_points,
            2,
        )

    @torch.jit.unused
    def _set_aux_loss(self, outputs_class, outputs_boxes, outputs_poly):
        return [
            {
                "pred_logits": a,
                "pred_boxes": b,
                "pred_polylines": c,
            }
            for a, b, c in zip(
                outputs_class[:-1], outputs_boxes[:-1], outputs_poly[:-1]
            )
        ]

    def forward(
        self, x: torch.Tensor, return_features: bool = False
    ) -> Dict[str, torch.Tensor]:
        B, L, _ = x.shape
        assert (
            L == self.grid_h * self.grid_w
        ), f"Expected {self.grid_h * self.grid_w} tokens, got {L}"

        dino_tokens = x
        src = self.input_proj(x)
        pos = self.pos_embed(B=B, H=self.grid_h, W=self.grid_w, device=x.device)
        query_pos, query_content = self._build_hierarchical_queries()

        reference_points = None
        if self.with_refine:
            reference_points = self.reference_points(query_pos).sigmoid()  # (P*K,2)
            reference_points = reference_points.unsqueeze(0).expand(B, -1, -1)

        mask = None
        hs, refs, memory = self.transformer(
            src=src,
            query_embed=query_pos,
            query_content=query_content,
            pos_embed=pos,
            mask=mask,
            reference_points=reference_points,
            reg_branches=self.reg_branches if self.with_refine else None,
            ref_point_head=self.ref_point_head if self.with_refine else None,
        )  # hs: (num_layers,B,P*K,D); refs: (num_layers,B,P*K,2) or None

        hs_poly = hs.view(
            hs.shape[0],
            B,
            self.num_polylines,
            self.num_points,
            hs.shape[-1],
        )  # (num_layers,B,P,K,D)
        outputs_class = self.class_embed(hs_poly.mean(dim=3))  # (num_layers,B,P,C+1)
        if self.with_refine:
            outputs_poly = refs.view(
                refs.shape[0], B, self.num_polylines, self.num_points, 2
            )  # (num_layers,B,P,K,2)
        else:
            outputs_poly = self._decode_polylines(hs, query_pos)
        outputs_boxes = box_xyxy_to_cxcywh(
            polyline_to_bbox_xyxy(outputs_poly)
        )  # (num_layers,B,P,4)

        out = {
            "pred_logits": outputs_class[-1],
            "pred_boxes": outputs_boxes[-1],
            "pred_polylines": outputs_poly[-1],
        }

        if return_features:
            out["memory"] = memory
            out["hs_last"] = hs_poly[-1].mean(dim=2)
            out["dino_tokens"] = dino_tokens

        if self.aux_loss:
            out["aux_outputs"] = self._set_aux_loss(
                outputs_class, outputs_boxes, outputs_poly
            )

        return out


class DetrPolylineFromImage(nn.Module):
    """
    Backbone (image -> feature map) + DetrPolylineFromEmbeddings (tokens -> polylines).

    Images must be (B, 3, pad_to, pad_to) with pad_to divisible by the backbone
    stride; the token grid is then (pad_to/stride, pad_to/stride).
    """

    def __init__(self, backbone: ResNet18UNetFeatures, detr: DetrPolylineFromEmbeddings):
        super().__init__()
        self.backbone = backbone
        self.detr = detr

    def forward(
        self, images: torch.Tensor, return_features: bool = False
    ) -> Dict[str, torch.Tensor]:
        feat = self.backbone(images)  # (B,C,h,w)
        B, C, h, w = feat.shape
        assert (h, w) == (self.detr.grid_h, self.detr.grid_w), (
            f"Feature grid {(h, w)} != detr grid {(self.detr.grid_h, self.detr.grid_w)}"
        )
        tokens = feat.flatten(2).transpose(1, 2)  # (B,h*w,C)
        return self.detr(tokens, return_features=return_features)


# -------------------------
# Matcher + Criterion for polylines
# -------------------------


@dataclass
class MatcherCost:
    class_cost: float = 1.0
    poly_cost: float = 5.0
    bbox_cost: float = 2.0
    bbox_giou_cost: float = 2.0


class HungarianMatcherPolyline(nn.Module):
    def __init__(self, cost: MatcherCost):
        super().__init__()
        self.cost = cost

    @torch.no_grad()
    def forward(
        self, outputs: Dict[str, torch.Tensor], targets: List[Dict[str, torch.Tensor]]
    ):
        """
        outputs:
          pred_logits: (B,Q,C+1)
          pred_boxes: (B,Q,4) cxcywh normalized
          pred_polylines: (B,Q,K,2) normalized
        """
        bs, num_queries = outputs["pred_logits"].shape[:2]
        out_prob = outputs["pred_logits"].softmax(-1)
        out_poly = outputs["pred_polylines"]
        out_box = outputs["pred_boxes"]

        indices = []
        for b in range(bs):
            tgt_ids = targets[b]["labels"]
            tgt_poly = targets[b]["polylines"]

            if tgt_poly.numel() == 0:
                indices.append(
                    (
                        torch.empty(0, dtype=torch.int64),
                        torch.empty(0, dtype=torch.int64),
                    )
                )
                continue

            cost_class = -out_prob[b][:, tgt_ids]

            Q = out_poly[b].shape[0]
            K = out_poly[b].shape[1]

            out_flat = out_poly[b].reshape(Q, 2 * K)
            tgt_flat = tgt_poly.reshape(tgt_poly.shape[0], 2 * K)
            tgt_rev = torch.flip(tgt_poly, dims=[1]).reshape(tgt_poly.shape[0], 2 * K)

            cost_fwd = torch.cdist(out_flat, tgt_flat, p=1) / float(2 * K)
            cost_rev = torch.cdist(out_flat, tgt_rev, p=1) / float(2 * K)
            cost_poly = torch.minimum(cost_fwd, cost_rev)

            C = (
                self.cost.class_cost * cost_class
                + self.cost.poly_cost * cost_poly
            )

            if self.cost.bbox_cost > 0 or self.cost.bbox_giou_cost > 0:
                tgt_bbox_xyxy = polyline_to_bbox_xyxy(tgt_poly)

                if self.cost.bbox_cost > 0:
                    tgt_bbox = box_xyxy_to_cxcywh(tgt_bbox_xyxy)
                    cost_bbox = torch.cdist(out_box[b], tgt_bbox, p=1) / 4.0
                    C = C + self.cost.bbox_cost * cost_bbox

                if self.cost.bbox_giou_cost > 0:
                    out_bbox_xyxy = box_cxcywh_to_xyxy(out_box[b]).clamp(0.0, 1.0)
                    cost_giou = -generalized_box_iou_xyxy(out_bbox_xyxy, tgt_bbox_xyxy)
                    C = C + self.cost.bbox_giou_cost * cost_giou

            C = C.cpu()

            row_ind, col_ind = linear_sum_assignment(C)
            indices.append(
                (
                    torch.as_tensor(row_ind, dtype=torch.int64),
                    torch.as_tensor(col_ind, dtype=torch.int64),
                )
            )
        return indices


class DetrPolylineCriterion(nn.Module):
    def __init__(
        self,
        num_classes: int,
        matcher: HungarianMatcherPolyline,
        eos_coef: float = 0.1,
        loss_poly: float = 5.0,
        loss_bbox: float = 2.0,
        loss_bbox_giou: float = 2.0,
        loss_smooth: float = 0.05,
        loss_card: float = 0.5,
        loss_len: float = 1.0,
        loss_dir: float = 0.5,
        aux_weight: float = 0.5,
    ):
        super().__init__()
        self.num_classes = num_classes
        self.matcher = matcher
        self.eos_coef = eos_coef

        self.loss_poly_w = loss_poly
        self.loss_bbox_w = loss_bbox
        self.loss_bbox_giou_w = loss_bbox_giou
        self.loss_smooth_w = loss_smooth
        self.loss_card_w = loss_card
        self.loss_len_w = loss_len
        self.loss_dir_w = loss_dir
        self.aux_weight = aux_weight

        empty_weight = torch.ones(num_classes + 1)
        empty_weight[-1] = eos_coef
        self.register_buffer("empty_weight", empty_weight)

    def forward(
        self,
        outputs: Dict[str, torch.Tensor],
        targets: List[Dict[str, torch.Tensor]],
    ) -> Dict[str, torch.Tensor]:
        outputs_without_aux = {k: v for k, v in outputs.items() if k != "aux_outputs"}

        losses = self._compute_losses(outputs_without_aux, targets, suffix="")
        total = losses["loss_total"]

        if "aux_outputs" in outputs:
            for i, aux_outputs in enumerate(outputs["aux_outputs"]):
                aux_losses = self._compute_losses(aux_outputs, targets, suffix="")
                total = total + self.aux_weight * aux_losses["loss_total"]

                for k, v in aux_losses.items():
                    losses[f"aux{i}_{k}"] = v

        losses["loss_total"] = total
        return losses

    def _compute_losses(
        self,
        outputs: Dict[str, torch.Tensor],
        targets: List[Dict[str, torch.Tensor]],
        suffix: str = "",
    ) -> Dict[str, torch.Tensor]:
        indices = self.matcher(outputs, targets)
        zero = outputs["pred_polylines"].new_tensor(0.0)

        loss_ce = self.loss_labels(outputs, targets, indices)
        loss_poly = self.loss_polylines(outputs, targets, indices)
        loss_bbox = (
            self.loss_boxes(outputs, targets, indices)
            if self.loss_bbox_w > 0
            else zero
        )
        loss_giou = (
            self.loss_bbox_giou(outputs, targets, indices)
            if self.loss_bbox_giou_w > 0
            else zero
        )
        loss_smooth = (
            self.loss_smoothness(outputs, indices) if self.loss_smooth_w > 0 else zero
        )
        loss_card = (
            self.loss_cardinality(outputs, targets) if self.loss_card_w > 0 else zero
        )
        if self.loss_len_w > 0 or self.loss_dir_w > 0:
            loss_len, loss_dir = self.loss_length_direction(outputs, targets, indices)
        else:
            loss_len, loss_dir = zero, zero

        loss_total = (
            loss_ce
            + self.loss_poly_w * loss_poly
            + self.loss_bbox_w * loss_bbox
            + self.loss_bbox_giou_w * loss_giou
            + self.loss_smooth_w * loss_smooth
            + self.loss_card_w * loss_card
            + self.loss_len_w * loss_len
            + self.loss_dir_w * loss_dir
        )

        return {
            f"loss_ce{suffix}": loss_ce,
            f"loss_poly{suffix}": loss_poly,
            f"loss_bbox{suffix}": loss_bbox,
            f"loss_bbox_giou{suffix}": loss_giou,
            f"loss_smooth{suffix}": loss_smooth,
            f"loss_card{suffix}": loss_card,
            f"loss_len{suffix}": loss_len,
            f"loss_dir{suffix}": loss_dir,
            f"loss_total{suffix}": loss_total,
        }

    def loss_labels(self, outputs, targets, indices):
        src_logits = outputs["pred_logits"]  # (B,Q,C+1)
        B, Q, _ = src_logits.shape

        target_classes = torch.full(
            (B, Q), self.num_classes, dtype=torch.int64, device=src_logits.device
        )

        for b, (src_idx, tgt_idx) in enumerate(indices):
            if len(src_idx) == 0:
                continue
            target_classes[b, src_idx] = targets[b]["labels"][tgt_idx]

        return F.cross_entropy(
            src_logits.transpose(1, 2), target_classes, weight=self.empty_weight
        )

    def loss_polylines(self, outputs, targets, indices):
        pred_poly = outputs["pred_polylines"]  # (B,Q,K,2)
        loss = pred_poly.new_tensor(0.0)
        n_matched = 0

        for b, (src_idx, tgt_idx) in enumerate(indices):
            if len(src_idx) == 0:
                continue

            s = pred_poly[b, src_idx]  # (M,K,2)
            t = targets[b]["polylines"][tgt_idx]  # (M,K,2)
            t_rev = torch.flip(t, dims=[1])  # (M,K,2)

            l1_fwd = F.l1_loss(s, t, reduction="none").sum(dim=(1, 2))  # (M,)
            l1_rev = F.l1_loss(s, t_rev, reduction="none").sum(dim=(1, 2))  # (M,)
            loss = loss + torch.minimum(l1_fwd, l1_rev).sum()
            n_matched += s.shape[0]

        n_matched = max(n_matched, 1)
        K = pred_poly.shape[2]
        return loss / (n_matched * K * 2.0)

    def loss_boxes(self, outputs, targets, indices):
        pred_box = outputs["pred_boxes"]  # cxcywh
        loss = pred_box.new_tensor(0.0)
        n_matched = 0

        for b, (src_idx, tgt_idx) in enumerate(indices):
            if len(src_idx) == 0:
                continue

            s = pred_box[b, src_idx]
            t_poly = targets[b]["polylines"][tgt_idx]
            t_box = box_xyxy_to_cxcywh(polyline_to_bbox_xyxy(t_poly))

            loss = loss + F.l1_loss(s, t_box, reduction="sum")
            n_matched += s.shape[0]

        n_matched = max(n_matched, 1)
        return loss / (n_matched * 4.0)

    def loss_bbox_giou(self, outputs, targets, indices):
        pred_box = outputs["pred_boxes"]
        loss = pred_box.new_tensor(0.0)
        n_matched = 0

        for b, (src_idx, tgt_idx) in enumerate(indices):
            if len(src_idx) == 0:
                continue

            s = box_cxcywh_to_xyxy(pred_box[b, src_idx]).clamp(0.0, 1.0)
            t_poly = targets[b]["polylines"][tgt_idx]
            t = polyline_to_bbox_xyxy(t_poly)

            giou = generalized_box_iou_xyxy(s, t).diag()
            loss = loss + (1.0 - giou).sum()
            n_matched += s.shape[0]

        n_matched = max(n_matched, 1)
        return loss / n_matched

    def loss_smoothness(self, outputs, indices):
        pred_poly = outputs["pred_polylines"]  # (B,Q,K,2)
        loss = pred_poly.new_tensor(0.0)
        n = 0

        for b, (src_idx, _) in enumerate(indices):
            if len(src_idx) == 0:
                continue
            p = pred_poly[b, src_idx]  # (M,K,2)
            if p.shape[1] < 3:
                continue
            d2 = p[:, 2:] - 2.0 * p[:, 1:-1] + p[:, :-2]  # (M,K-2,2)
            loss = loss + (d2**2).mean()
            n += 1

        if n == 0:
            return pred_poly.new_tensor(0.0)
        return loss / n

    def loss_cardinality(self, outputs, targets):
        pred_logits = outputs["pred_logits"]
        pred_classes = pred_logits.argmax(-1)
        pred_counts = (pred_classes != self.num_classes).sum(dim=1).float()

        tgt_counts = torch.as_tensor(
            [len(t["labels"]) for t in targets],
            dtype=torch.float32,
            device=pred_logits.device,
        )
        return F.l1_loss(pred_counts, tgt_counts)

    def loss_length_direction(self, outputs, targets, indices):
        """
        Length and direction losses for matched polylines.

        Important:
        - The forward/reverse GT orientation is chosen using the same ordered L1
        criterion as loss_polylines.
        - This avoids one loss supervising the forward order while another loss
        supervises the reversed order.
        - Direction loss uses a larger epsilon than 1e-6 because predicted adjacent
        points can collapse early in training, making direction nearly undefined.
        """
        pred_poly = outputs["pred_polylines"]  # (B, Q, K, 2)

        loss_len = pred_poly.new_tensor(0.0)
        loss_dir = pred_poly.new_tensor(0.0)
        n_matched = 0

        dir_eps = 1e-3
        gt_seg_eps = 1e-6

        for b, (src_idx, tgt_idx) in enumerate(indices):
            if len(src_idx) == 0:
                continue

            s = pred_poly[b, src_idx]                  # (M, K, 2)
            t = targets[b]["polylines"][tgt_idx]       # (M, K, 2)
            t_rev = torch.flip(t, dims=[1])            # (M, K, 2)

            # Choose orientation using the same logic as loss_polylines.
            l1_fwd = F.l1_loss(s, t, reduction="none").sum(dim=(1, 2))      # (M,)
            l1_rev = F.l1_loss(s, t_rev, reduction="none").sum(dim=(1, 2))  # (M,)

            use_rev = (l1_rev < l1_fwd).detach()  # boolean, no gradient needed
            t_ord = torch.where(use_rev[:, None, None], t_rev, t)

            # Segment vectors.
            s_v = s[:, 1:] - s[:, :-1]          # (M, K-1, 2)
            t_v = t_ord[:, 1:] - t_ord[:, :-1]  # (M, K-1, 2)

            # Segment length loss.
            s_len = torch.linalg.norm(s_v, dim=-1)  # (M, K-1)
            t_len = torch.linalg.norm(t_v, dim=-1)  # (M, K-1)

            len_per_poly = F.l1_loss(s_len, t_len, reduction="none").mean(dim=1)
            loss_len = loss_len + len_per_poly.sum()

            # Direction loss.
            # Mask invalid GT segments, just in case duplicate GT points exist.
            valid = (t_len > gt_seg_eps).float()  # (M, K-1)

            s_norm = torch.linalg.norm(s_v, dim=-1, keepdim=True).clamp_min(dir_eps)
            t_norm = torch.linalg.norm(t_v, dim=-1, keepdim=True).clamp_min(dir_eps)

            s_dir = s_v / s_norm
            t_dir = t_v / t_norm

            cosine = (s_dir * t_dir).sum(dim=-1).clamp(-1.0, 1.0)  # (M, K-1)
            dir_loss = 1.0 - cosine

            dir_per_poly = (dir_loss * valid).sum(dim=1) / valid.sum(dim=1).clamp_min(1.0)
            loss_dir = loss_dir + dir_per_poly.sum()

            n_matched += s.shape[0]

        if n_matched == 0:
            z = pred_poly.new_tensor(0.0)
            return z, z

        return loss_len / n_matched, loss_dir / n_matched


# -------------------------
# Dataset and collate
# -------------------------


def _rot90_polylines(polylines: np.ndarray, k: int, size: int) -> np.ndarray:
    """
    Apply np.rot90(image, k) coordinate mapping to xy polylines on a square
    image of `size` pixels: one CCW rotation maps (x, y) -> (y, size-1-x).
    """
    for _ in range(k % 4):
        x = polylines[..., 0].copy()
        y = polylines[..., 1].copy()
        polylines[..., 0] = y
        polylines[..., 1] = (size - 1) - x
    return polylines


class DetrPolylineImageDataset(Dataset):
    """
    images from image_dir (pos_*.png etc.), GT from polyline_dir NPZs produced
    by scripts/data/convert_pdok_polylines_to_detr_polyline.py:
      polylines: (Ni,K,2) xy pixel coords
      labels: (Ni,)
      image_size: (2,) (H,W)

    Returns:
      image: (3, pad_to, pad_to) float, ImageNet-normalized, zero-padded
             bottom-right from (H,W)
      target: polylines normalized by (pad_to - 1) in [0,1]
    """

    IMAGE_SUFFIXES = [".png", ".jpg", ".jpeg", ".tif", ".tiff"]

    def __init__(
        self,
        image_dir: Path,
        polyline_dir: Path,
        num_points: int = 20,
        pad_to: int = 1024,
        augment: bool = False,
    ):
        self.image_dir = Path(image_dir)
        self.files = sorted(Path(polyline_dir).glob("*.npz"))
        self.num_points = num_points
        self.pad_to = pad_to
        self.augment = augment

    def __len__(self):
        return len(self.files)

    def _image_path(self, stem: str) -> Path:
        for suffix in self.IMAGE_SUFFIXES:
            candidate = self.image_dir / f"{stem}{suffix}"
            if candidate.exists():
                return candidate
        raise FileNotFoundError(f"No image for {stem} in {self.image_dir}")

    def __getitem__(self, idx: int):
        npz_path = self.files[idx]
        d = np.load(npz_path)

        polylines = np.ascontiguousarray(d["polylines"]).astype(np.float32)
        labels = torch.from_numpy(np.ascontiguousarray(d["labels"])).long()
        H, W = d["image_size"].tolist()

        if polylines.shape[0] > 0 and polylines.shape[1] != self.num_points:
            raise ValueError(
                f"{npz_path.name}: expected K={self.num_points}, got {polylines.shape[1]}"
            )

        image = Image.open(self._image_path(npz_path.stem)).convert("RGB")
        if image.size != (W, H):
            raise ValueError(
                f"{npz_path.stem}: image size {image.size} != npz image_size {(W, H)}"
            )
        arr = np.asarray(image, dtype=np.float32) / 255.0  # (H,W,3)

        if self.augment:
            if H != W:
                raise ValueError("augment=True requires square images")
            if np.random.rand() < 0.5:
                arr = arr[:, ::-1]
                polylines[..., 0] = (W - 1) - polylines[..., 0]
            if np.random.rand() < 0.5:
                arr = arr[::-1]
                polylines[..., 1] = (H - 1) - polylines[..., 1]
            k = np.random.randint(0, 4)
            if k:
                arr = np.rot90(arr, k)
                polylines = _rot90_polylines(polylines, k, W)

        if H > self.pad_to or W > self.pad_to:
            raise ValueError(f"{npz_path.stem}: image {(H, W)} larger than pad_to")
        padded = np.zeros((self.pad_to, self.pad_to, 3), dtype=np.float32)
        padded[:H, :W] = arr

        x = torch.from_numpy(padded).permute(2, 0, 1).contiguous()
        x = (x - IMAGENET_MEAN) / IMAGENET_STD

        polylines = torch.from_numpy(np.ascontiguousarray(polylines)).float()
        if polylines.numel() > 0:
            polylines = (polylines / float(self.pad_to - 1)).clamp(0, 1)

        target = {
            "labels": labels,
            "polylines": polylines,
            "image_size": np.asarray([H, W], dtype=np.int32),
            "pad_size": self.pad_to,
            "stem": npz_path.stem,
        }
        return x, target


class DetrPolylineImageFileListDataset(DetrPolylineImageDataset):
    def __init__(
        self,
        split_file: Path,
        image_dir: Path,
        num_points: int = 20,
        pad_to: int = 1024,
        augment: bool = False,
    ):
        split_file = Path(split_file)
        self.image_dir = Path(image_dir)
        self.files = []
        with open(split_file) as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                path = Path(line)
                if not path.is_absolute():
                    path = split_file.parent / path
                self.files.append(path)

        self.num_points = num_points
        self.pad_to = pad_to
        self.augment = augment


def detr_polyline_collate_fn(batch):
    images, targets = zip(*batch)
    images = torch.stack(images, dim=0)  # (B,3,pad,pad)
    return images, list(targets)


@torch.no_grad()
def preview_dataset(dataset, out_dir: Path, n: int = 8, dpi: int = 150):
    """
    Render exactly what the model sees: the padded/normalized (and possibly
    augmented) image tensor with its GT polylines, denormalized for display.
    Point order shown as color gradient (dark = first point).
    """
    out_dir.mkdir(parents=True, exist_ok=True)
    n = min(n, len(dataset))
    for i in range(n):
        x, target = dataset[i]
        image = (x * IMAGENET_STD + IMAGENET_MEAN).clamp(0, 1)
        image = image.permute(1, 2, 0).numpy()
        S = image.shape[0]

        polys = target["polylines"]
        fig, ax = plt.subplots(figsize=(S / dpi, S / dpi), dpi=dpi)
        ax.imshow(image)
        cmap = plt.get_cmap("tab10")
        for j, poly in enumerate(polys):
            p = poly.numpy() * (S - 1)
            color = cmap(j % 10)
            ax.plot(p[:, 0], p[:, 1], "-", color=color, linewidth=1.0)
            order = np.linspace(0.3, 1.0, p.shape[0])
            ax.scatter(p[:, 0], p[:, 1], c=order, cmap="viridis", s=4, zorder=3)
            ax.plot(p[0, 0], p[0, 1], "o", color=color, markersize=5, zorder=4)
        ax.set_xlim(0, S - 1)
        ax.set_ylim(S - 1, 0)
        ax.axis("off")
        fig.tight_layout(pad=0)
        fig.savefig(out_dir / f"{target['stem']}_{i:02d}.png", bbox_inches="tight")
        plt.close(fig)
    print(f"Wrote {n} preview images to {out_dir}")


# -------------------------
# Training / eval / inference
# -------------------------


def tb_add_losses(writer, epoch: int, losses: dict, stage: str):
    wanted = {"loss_total"}
    d = {f"{stage}_{k}": float(v) for k, v in losses.items() if k in wanted}
    writer.add_scalars("losses", d, epoch)


def train_one_epoch(loader, model, criterion, optimizer, device):
    model.train()
    sums = {
        "loss_ce": 0.0,
        "loss_poly": 0.0,
        "loss_bbox": 0.0,
        "loss_bbox_giou": 0.0,
        "loss_smooth": 0.0,
        "loss_card": 0.0,
        "loss_len": 0.0,
        "loss_dir": 0.0,
        "loss_total": 0.0,
    }
    n = 0

    for feats, targets in loader:
        feats = feats.to(device)
        for t in targets:
            t["labels"] = t["labels"].to(device)
            t["polylines"] = t["polylines"].to(device)

        optimizer.zero_grad(set_to_none=True)
        outputs = model(feats)
        loss_dict = criterion(outputs, targets)
        loss = loss_dict["loss_total"]
        loss.backward()
        torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)
        # a = {n:round(p.grad.max().item(),2) for n, p in model.named_parameters()}
        # {k:v for k, v in a.items() if v == max(a.values())}
        optimizer.step()

        bs = feats.size(0)
        n += bs
        for k in sums:
            if k in loss_dict:
                sums[k] += float(loss_dict[k].detach().item()) * bs

    for k in sums:
        sums[k] /= max(n, 1)
    return sums


@torch.no_grad()
def eval_one_epoch(loader, model, criterion, device):
    model.eval()
    sums = {
        "loss_ce": 0.0,
        "loss_poly": 0.0,
        "loss_bbox": 0.0,
        "loss_bbox_giou": 0.0,
        "loss_smooth": 0.0,
        "loss_card": 0.0,
        "loss_len": 0.0,
        "loss_dir": 0.0,
        "loss_total": 0.0,
    }
    n = 0

    for feats, targets in loader:
        feats = feats.to(device)
        for t in targets:
            t["labels"] = t["labels"].to(device)
            t["polylines"] = t["polylines"].to(device)

        outputs = model(feats)
        loss_dict = criterion(outputs, targets)

        bs = feats.size(0)
        n += bs
        for k in sums:
            if k in loss_dict:
                sums[k] += float(loss_dict[k].detach().item()) * bs

    for k in sums:
        sums[k] /= max(n, 1)
    return sums


@torch.no_grad()
def detr_polyline_inference(
    model,
    images: torch.Tensor,
    image_sizes: List[Tuple[int, int]],
    pad_sizes: List[int],
    score_thresh: float = 0.5,
    topk: int = 100,
    device: torch.device | None = None,
):
    model.eval()
    if device is not None:
        images = images.to(device)
        model = model.to(device)

    outputs = model(images)
    logits = outputs["pred_logits"]  # (B,Q,C+1)
    polylines = outputs["pred_polylines"]  # (B,Q,K,2) normalized
    boxes = outputs["pred_boxes"]  # cxcywh normalized

    prob = F.softmax(logits, dim=-1)  # (B,Q,C+1)
    scores_all, labels_all = prob[..., :-1].max(dim=-1)  # exclude "no-object" -> (B,Q)

    B, Q = scores_all.shape
    results = []

    for b in range(B):
        H, W = image_sizes[b]
        S = pad_sizes[b]  # polylines were normalized by (pad_size - 1)

        scores = scores_all[b]
        labels = labels_all[b]
        polys = polylines[b]  # (Q,K,2)
        bx = boxes[b]

        keep = scores >= score_thresh
        if keep.any():
            scores = scores[keep]
            labels = labels[keep]
            polys = polys[keep]
            bx = bx[keep]
        else:
            results.append(
                {
                    "scores": scores.new_zeros((0,)),
                    "labels": labels.new_zeros((0,), dtype=torch.long),
                    "polylines_norm": polys.new_zeros((0, polys.shape[1], 2)),
                    "polylines_px": polys.new_zeros((0, polys.shape[1], 2)),
                    "boxes_norm": bx.new_zeros((0, 4)),
                    "boxes_px_xyxy": bx.new_zeros((0, 4)),
                }
            )
            continue

        if scores.numel() > topk:
            top_idx = torch.topk(scores, k=topk, largest=True).indices
            scores = scores[top_idx]
            labels = labels[top_idx]
            polys = polys[top_idx]
            bx = bx[top_idx]

        polys_px = polys.clone()
        polys_px[..., 0] = (polys_px[..., 0] * float(S - 1)).clamp(0, W - 1)
        polys_px[..., 1] = (polys_px[..., 1] * float(S - 1)).clamp(0, H - 1)

        bx_xyxy = box_cxcywh_to_xyxy(bx).clone()
        bx_xyxy[..., 0] = (bx_xyxy[..., 0] * float(S - 1)).clamp(0, W - 1)
        bx_xyxy[..., 1] = (bx_xyxy[..., 1] * float(S - 1)).clamp(0, H - 1)
        bx_xyxy[..., 2] = (bx_xyxy[..., 2] * float(S - 1)).clamp(0, W - 1)
        bx_xyxy[..., 3] = (bx_xyxy[..., 3] * float(S - 1)).clamp(0, H - 1)

        results.append(
            {
                "scores": scores.detach().cpu(),
                "labels": labels.detach().cpu(),
                "polylines_norm": polys.detach().cpu(),
                "polylines_px": polys_px.detach().cpu(),
                "boxes_norm": bx.detach().cpu(),
                "boxes_px_xyxy": bx_xyxy.detach().cpu(),
            }
        )

    return results


@torch.no_grad()
def infer_model(loader, model, device, cfg):
    model.eval()

    out_dir = (
        Path(cfg.infer_out_dir)
        if cfg.infer_out_dir is not None
        else cfg.save_path / f"{cfg.exp}_inference"
    )
    pred_dir = out_dir / "polylines"
    pred_dir.mkdir(parents=True, exist_ok=True)

    for images, targets in tqdm(loader, disable=cfg.disable_tqdm):
        image_sizes = []
        pad_sizes = []
        for t in targets:
            size = t["image_size"]
            if torch.is_tensor(size):
                size = size.tolist()
            elif hasattr(size, "tolist"):
                size = size.tolist()
            image_sizes.append(size)
            pad_sizes.append(int(t["pad_size"]))

        preds = detr_polyline_inference(
            model=model,
            images=images,
            image_sizes=image_sizes,
            pad_sizes=pad_sizes,
            score_thresh=cfg.infer_score_thresh,
            topk=cfg.infer_topk,
            device=device,
        )

        for pred, target, image_size in zip(preds, targets, image_sizes):
            np.savez_compressed(
                pred_dir / f"{target['stem']}.npz",
                polylines=pred["polylines_px"].numpy(),
                polylines_norm=pred["polylines_norm"].numpy(),
                scores=pred["scores"].numpy(),
                labels=pred["labels"].numpy(),
                image_size=np.asarray(image_size, dtype=np.int32),
            )


# =========================================================


def load_checkpoint_flexible(
    module: nn.Module, ckpt_path: Path, key_candidates=None, strict: bool = True
):
    ckpt = torch.load(ckpt_path, map_location="cpu")
    if key_candidates is None:
        key_candidates = ["model", "state_dict"]

    state = None
    for k in key_candidates:
        if k in ckpt:
            state = ckpt[k]
            break

    if state is None:
        state = ckpt

    missing, unexpected = module.load_state_dict(state, strict=strict)
    print(f"Epoch:{ckpt['epoch']}")
    print(f"Loaded checkpoint from {ckpt_path}")
    print(f"  missing keys: {len(missing)}")
    print(f"  unexpected keys: {len(unexpected)}")
    return ckpt


def save_train_val_split_files(dataset, train_ds, val_ds, split_dir: Path):
    split_dir.mkdir(parents=True, exist_ok=True)

    split_paths = {
        "train": [dataset.files[i] for i in train_ds.indices],
        "val": [dataset.files[i] for i in val_ds.indices],
    }

    for split, files in split_paths.items():
        with open(split_dir / f"{split}.txt", "w") as f:
            for path in files:
                f.write(str(path) + "\n")

    print(f"Saved train/val split to {split_dir}")


# -------------------------
# Main
# -------------------------


def main(cfg):
    set_seed(cfg.seed)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    if device.type == "cuda":
        print(f"Using device: {torch.cuda.get_device_properties()}")

    stage = FEATURE_STAGES[cfg.feature_stage]
    assert cfg.pad_to % stage["stride"] == 0
    grid = cfg.pad_to // stage["stride"]

    backbone = ResNet18UNetFeatures(
        ckpt_path=cfg.backbone_ckpt,
        feature_stage=cfg.feature_stage,
        frozen=cfg.freeze_backbone,
    )
    detr = DetrPolylineFromEmbeddings(
        in_dim=stage["channels"],
        num_classes=cfg.num_classes,
        num_polylines=cfg.num_polylines,
        d_model=cfg.d_model,
        nhead=cfg.nhead,
        num_encoder_layers=cfg.num_encoder_layers,
        num_decoder_layers=cfg.num_decoder_layers,
        dim_feedforward=cfg.dim_feedforward,
        dropout=cfg.dropout,
        grid_size=(grid, grid),
        num_points=cfg.num_points,
        aux_loss=cfg.aux_loss,
        query_embed_mode=cfg.query_embed_mode,
        with_refine=cfg.with_refine,
    )
    model = DetrPolylineFromImage(backbone, detr).to(device)
    n_trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    print(
        f"Feature stage: {cfg.feature_stage} (stride {stage['stride']}, "
        f"grid {grid}x{grid}), trainable params: {n_trainable / 1e6:.1f}M"
    )

    if cfg.mode == "preview":
        preview_ds = DetrPolylineImageDataset(
            image_dir=cfg.image_dir,
            polyline_dir=cfg.polyline_dir,
            num_points=cfg.num_points,
            pad_to=cfg.pad_to,
            augment=cfg.augment,
        )
        preview_dataset(preview_ds, Path(cfg.preview_out_dir), n=cfg.preview_n)
        return

    if cfg.mode == "infer":
        if cfg.infer_ckpt is None:
            raise ValueError("For mode='infer', cfg.infer_ckpt must be set.")
        load_checkpoint_flexible(model, cfg.infer_ckpt, key_candidates=["model"])

        if cfg.infer_split_file is not None:
            infer_ds = DetrPolylineImageFileListDataset(
                split_file=cfg.infer_split_file,
                image_dir=cfg.image_dir,
                num_points=cfg.num_points,
                pad_to=cfg.pad_to,
                augment=False,
            )
        elif cfg.infer_polyline_dir is not None:
            infer_ds = DetrPolylineImageDataset(
                image_dir=cfg.image_dir,
                polyline_dir=cfg.infer_polyline_dir,
                num_points=cfg.num_points,
                pad_to=cfg.pad_to,
                augment=False,
            )
        else:
            raise ValueError(
                "For mode='infer', set cfg.infer_split_file or cfg.infer_polyline_dir."
            )

        infer_loader = DataLoader(
            infer_ds,
            batch_size=cfg.batch_size,
            shuffle=False,
            num_workers=cfg.num_workers,
            collate_fn=detr_polyline_collate_fn,
            persistent_workers=cfg.num_workers > 0,
        )
        infer_model(infer_loader, model, device, cfg)
        return

    if cfg.mode != "train":
        raise ValueError("cfg.mode must be 'train', 'infer' or 'preview'.")

    # Two dataset views over the same files: augmentation only on train.
    dataset = DetrPolylineImageDataset(
        image_dir=cfg.image_dir,
        polyline_dir=cfg.polyline_dir,
        num_points=cfg.num_points,
        pad_to=cfg.pad_to,
        augment=cfg.augment,
    )
    dataset_plain = DetrPolylineImageDataset(
        image_dir=cfg.image_dir,
        polyline_dir=cfg.polyline_dir,
        num_points=cfg.num_points,
        pad_to=cfg.pad_to,
        augment=False,
    )
    n_train = int(0.8 * len(dataset))
    perm = torch.randperm(
        len(dataset), generator=torch.Generator().manual_seed(cfg.seed)
    ).tolist()
    train_ds = torch.utils.data.Subset(dataset, perm[:n_train])
    val_ds = torch.utils.data.Subset(dataset_plain, perm[n_train:])
    print(f"Dataset: total={len(dataset)}, train={len(train_ds)}, val={len(val_ds)}")

    if cfg.save_splits:
        split_dir = (
            Path(cfg.split_dir)
            if cfg.split_dir is not None
            else cfg.save_path / "splits"
        )
        save_train_val_split_files(dataset, train_ds, val_ds, split_dir)

    # persistent_workers avoids respawning worker processes every epoch, which
    # dominates the epoch time for small datasets.
    train_loader = DataLoader(
        train_ds,
        batch_size=cfg.batch_size,
        shuffle=True,
        num_workers=cfg.num_workers,
        collate_fn=detr_polyline_collate_fn,
        persistent_workers=cfg.num_workers > 0,
    )
    eval_loader = DataLoader(
        val_ds,
        batch_size=cfg.batch_size,
        shuffle=False,
        num_workers=cfg.num_workers,
        collate_fn=detr_polyline_collate_fn,
        persistent_workers=cfg.num_workers > 0,
    )

    matcher = HungarianMatcherPolyline(
        MatcherCost(
            class_cost=cfg.class_cost,
            poly_cost=cfg.poly_cost,
            bbox_cost=cfg.bbox_cost,
            bbox_giou_cost=cfg.loss_bbox_giou,
        )
    )
    criterion = DetrPolylineCriterion(
        num_classes=cfg.num_classes,
        matcher=matcher,
        eos_coef=cfg.eos_coef,
        loss_poly=cfg.loss_poly,
        loss_bbox=cfg.loss_bbox,
        loss_bbox_giou=cfg.loss_bbox_giou,
        loss_smooth=cfg.loss_smooth,
        loss_card=cfg.loss_card,
        loss_len=cfg.loss_len,
        loss_dir=cfg.loss_dir,
        aux_weight=cfg.aux_weight,
    )
    criterion.to(device)

    if cfg.resume_ckpt is not None:
        load_checkpoint_flexible(model, cfg.resume_ckpt, key_candidates=["model"])

    tb_dir = cfg.save_path / f"tensorboard/{cfg.exp}"
    tb_dir.mkdir(parents=True, exist_ok=True)
    writer = tensorboard.SummaryWriter(tb_dir)
    best_val = float("inf")

    optimizer = torch.optim.AdamW(
        [p for p in model.parameters() if p.requires_grad],
        lr=cfg.max_lr,
        weight_decay=cfg.weight_decay,
    )
    scheduler = torch.optim.lr_scheduler.CosineAnnealingLR(
        optimizer, T_max=cfg.n_epochs, eta_min=1e-6
    )

    for epoch in tqdm(range(1, cfg.n_epochs + 1), disable=cfg.disable_tqdm):
        s_time = datetime.now().replace(microsecond=0)
        print(f"Epoch {epoch:03d}/{cfg.n_epochs} starting at {s_time}")

        train_losses = train_one_epoch(
            train_loader, model, criterion, optimizer, device
        )
        run_eval = (epoch % cfg.eval_every == 0) or (epoch == cfg.n_epochs)
        eval_losses = (
            eval_one_epoch(eval_loader, model, criterion, device)
            if run_eval
            else None
        )

        e_time = datetime.now().replace(microsecond=0)
        msg = (
            f"Epoch {epoch:03d}/{cfg.n_epochs} "
            f"train_total={train_losses['loss_total']:.4f} "
            f"(ce={train_losses['loss_ce']:.4f}, poly={train_losses['loss_poly']:.4f}, "
            f"bbox_giou={train_losses['loss_bbox_giou']:.4f}, smooth={train_losses['loss_smooth']:.4f})"
        )
        if eval_losses is not None:
            msg += (
                f" eval_total={eval_losses['loss_total']:.4f} "
                f"(ce={eval_losses['loss_ce']:.4f}, poly={eval_losses['loss_poly']:.4f}, "
                f"bbox_giou={eval_losses['loss_bbox_giou']:.4f}, smooth={eval_losses['loss_smooth']:.4f})"
            )
        print(msg)
        print(
            f"Epoch {epoch:03d}/{cfg.n_epochs} finished at {e_time} (duration {e_time - s_time})"
        )

        tb_add_losses(writer, epoch, train_losses, "train")
        if eval_losses is not None:
            tb_add_losses(writer, epoch, eval_losses, "eval")

        ckpt = {
            "epoch": epoch,
            "model": model.state_dict(),
            # "optimizer": optimizer.state_dict(),
            # "train_losses": train_losses,
            # "eval_losses": eval_losses,
            # "cfg": OmegaConf.to_container(cfg, resolve=True),
        }
        if eval_losses is not None and eval_losses["loss_total"] < best_val:
            best_val = eval_losses["loss_total"]
            torch.save(ckpt, cfg.save_path / f"best_{cfg.exp}.pt")
            print(f"Saved best: {best_val:.4f} at epoch {epoch}")
        if epoch % cfg.save_every == 0:
            torch.save(ckpt, cfg.save_path / f"{cfg.exp}_{epoch}.pt")
        # scheduler.step()

    torch.save(ckpt, cfg.save_path / f"{cfg.exp}.pt")
    print(f"Saved final model: {best_val:.4f} at epoch {epoch}")


if __name__ == "__main__":
    cfg = dict(
        mode="infer",  # "train", "infer" or "preview"
        exp="detr_unet_polyline_3",
        save_path=Path("/home/fatemeh/Downloads/hedge/results/training"),
        # data (from scripts/data/convert_pdok_polylines_to_detr_polyline.py)
        image_dir=Path("/home/fatemeh/Downloads/hedge/results/pdok_dataset2/images"),
        polyline_dir=Path(
            "/home/fatemeh/Downloads/hedge/results/pdok_dataset2_detr/polylines"
        ),
        pad_to=1024,  # images zero-padded 1000 -> 1024 (divisible by 32)
        augment=False,  # flip/rot90 of image + polylines (train split only)
        # backbone
        backbone_ckpt=Path(
            "/home/fatemeh/Downloads/hedge/snellius/semseg_unet/4/best_4.pt"
        ),
        feature_stage="up3",  # "up3": stride 16, 64x64 tokens; "enc4": stride 32, 32x32
        freeze_backbone=True,
        num_points=20,
        num_polylines=60,  # polyline instance queries (max ~50 GT per image)
        num_classes=1,
        # base model
        d_model=256,
        nhead=8,
        num_encoder_layers=1,
        num_decoder_layers=4,
        dim_feedforward=1024,
        dropout=0.01,  # default 0.1
        aux_loss=True,
        query_embed_mode="detr",  # "detr" or "legacy"
        with_refine=True,  # per-layer reference-point refinement (MapTR-style)
        eos_coef=0.05,
        # criterion and matcher
        class_cost=1.0,
        poly_cost=5.0,
        bbox_cost=0.0,
        loss_poly=5.0,
        loss_bbox=0.0,
        loss_bbox_giou=0.0,
        loss_smooth=0.0,
        loss_card=0.0,
        loss_len=0.0,
        loss_dir=0.0, # 0.005
        aux_weight=0.5,
        # optimizer / training
        n_epochs=2000,
        batch_size=4,  # images are 1024x1024; up3 gives 4096 tokens
        num_workers=8,
        max_lr=1e-4,
        weight_decay=1e-2,
        disable_tqdm=True,
        save_every=2000,
        eval_every=1,  # evaluate every k epochs (best checkpoint only on eval epochs)
        seed=42,
        # data splits (train/val, optional)
        save_splits=True,
        split_dir=Path("/home/fatemeh/Downloads/hedge/results/pdok_dataset2_detr"),
        # checkpoints
        resume_ckpt=None,
        # preview
        preview_out_dir=Path(
            "/home/fatemeh/Downloads/hedge/results/pdok_dataset2_detr/preview"
        ),
        preview_n=10,
        # inference
        infer_ckpt=Path(
            "/home/fatemeh/Downloads/hedge/results/training/detr_unet_polyline_2.pt"
        ),
        infer_split_file=Path(
            "/home/fatemeh/Downloads/hedge/results/pdok_dataset2_detr/train.txt"
        ),
        infer_polyline_dir=None,
        infer_out_dir=Path(
            "/home/fatemeh/Downloads/hedge/results/pdok_dataset2_detr/inference"
        ),
        infer_score_thresh=0.5,
        infer_topk=60,
    )
    main(OmegaConf.create(cfg))
