"""
Dataset is generated by scripts/data/{build_pdok_wms_dataset.py,convert_to_ultralytics_format.py}
"""

from ultralytics import YOLO


def main():
    model = YOLO("yolo26x.pt")
    model.train(
        # data="/home/fkarimineja/data/hedge/pdok_dataset_yolo/dataset.yaml",
        data="/home/fatemeh/Downloads/hedge/results/pdok_dataset_yolo/dataset.yaml",
        epochs=1,
        imgsz=1000,
    )


if __name__ == "__main__":
    main()
